import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import Background from "@/components/Background";

export const metadata: Metadata = {
  title: "Prompt Brawl",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased font-rubik`}>
        <Toaster position="top-center" />

        <Background>{children}</Background>
      </body>
    </html>
  );
}
